### ISSUE TITLE
Add support to ssd1306

### ISSUE THREAD

**Issue by ilbossdelfaidate** [Pwnagotchi-Unofficial/minigotchi#110]
I believe that adding a 1306 or SH1106 SSD screen where you can see the logs or data sent via serial to the project is very useful because if you want to bring the ESP to evaluate whether there are any errors, turning on a PC and connecting it via serial becomes complicated

**Comment by nothingbutlucas** [comment]
Already supported: https://github.com/Pwnagotchi-Unofficial/minigotchi/pull/106
At least the shield for the wemos d1

**Comment by dj1ch** [comment]
As much as I want to put out a new release with that PR, recently there's been issues with Pwnagotchi detection where the ESP would literally crash. I hope to get this patched within this week, I'll be sure to let you know when this is fixed

**Comment by nothingbutlucas** [comment]
Oh I notice that, but I thought maybe it was my pwnagotchi... the problem is on the json parsing, right? Let me know if I can give u a hand with something

**Comment by dj1ch** [comment]
> Oh I notice that, but I thought maybe it was my pwnagotchi... the problem is on the JSON parsing, right? Let me know if I can give u a hand with something

The json parsing issue was just with the pwnagotchi stats being shown through its beacon frame's json. The actual problem with the crashing however could be the pwnagotchi callback itself.

**Comment by dj1ch** [comment]
> Already supported: #106 At least the shield for the wemos d1

also someone on the discord was able to get it to work with the 0.96 SSD1306 screen, that one is also supported to ig, maybe I could make a config value to set the screen size and stuff.

**Comment by ilbossdelfaidate** [comment]
I managed to start the ssd 1306 0.96 screen with the beta 3.0.2 if you are interested I will send you the lines of code , in discord i send the video

**Comment by dj1ch** [comment]
> I managed to start the ssd 1306 0.96 screen with the beta 3.0.2 if you are interested I will send you the lines of code , in discord i send the video

gotcha, if needed you can make a pr. i also made some recent changes to the [display.cpp](https://github.com/Pwnagotchi-Unofficial/minigotchi/blob/development/minigotchi/display.cpp) and [display.h](https://github.com/Pwnagotchi-Unofficial/minigotchi/blob/development/minigotchi/display.h) for the SSD1306 if you wanna make sure that it works, although you'll just need to adjust some configuration in `config.cpp` for configuration related to screens to suit your screen. the current screens I have added are `SSD1306` and `WEMOS_OLED_SHIELD`

**Comment by ilbossdelfaidate** [comment]
i send you a pm on discord with screen and full code vith edit
