### ISSUE TITLE
Error on compilation - SSD1306 implementation

### ISSUE THREAD

**Issue by nothingbutlucas** [Pwnagotchi-Unofficial/minigotchi#121]
Hi!
Building this again I found an error on compilation with the new screen SSD1306 implementation (Not the shield).

I'm using the last release `v3.1.1-beta`.

**Describe the bug**

This is the error on compilation step:

```
/minigotchi/display.cpp: In static member function 'static void Display::startScreen()':
/minigotchi/display.cpp:12:117: error: no matching function for call to 'Adafruit_SSD1306::Adafruit_SSD1306(int, int, TwoWire*, int)'
       adafruit_display = new Adafruit_SSD1306(SSD1306_SCREEN_WIDTH, SSD1306_SCREEN_HEIGHT, &Wire, SSD1306_OLED_RESET);
```

**To Reproduce**
1. Build the project.

**Expected behavior**
The build should not break.

**Screenshots**

I have the wemos oled shield so to bypass this error I commented the lines 12 and 13 of the `display.cpp` file:

![imagen](https://github.com/Pwnagotchi-Unofficial/minigotchi/assets/69118979/7e4977fa-4c95-4cbd-b48e-f65acda6b271)

I have a clean installation of arduino IDE with the libraries for this project only:

![imagen](https://github.com/Pwnagotchi-Unofficial/minigotchi/assets/69118979/d98ab068-d7e9-4580-a3ba-199987b366e9)

I think that the mini oled library it's not compatible with the SSD1306 regular screen... But I can not test it because I don't have that screen.

Commenting the lines 12 and 13 like I said before "works" and do not break the building process.

Please let me know if u need any more details, thanks.

**Comment by dj1ch** [comment]
The problem is the libraries, I think you'll need to install the SSD1306 library from Adafruit if you want to use the basic SSD1306, the Wemos library being used currently isn't compatible. I can make fixes to the Install Guide if needed.

**Comment by dj1ch** [comment]
Seems like this is stale now, the problem should  have been fixed in the new release.
