### ISSUE TITLE
Pwnagotchi stuck as found

### ISSUE THREAD

**Issue by matrix224** [Pwnagotchi-Unofficial/minigotchi#126]
I apologize if I missed something and this is wrong, but I figured I should note it just in case regardless. I haven't encountered this myself, but happened to notice it when looking over the code.

In Pwnagotchi.cpp, when another pwnagotchi is found, it sets `pwnagotchiDetected` to true. But it looks like it never gets reset to false, so in any subsequent calls to `Pwnagotchi::detect()` after a pwnagotchi has been found, I think it would always be considered as having found one. It doesn't really matter currently since it doesn't do any special handling when it's true anyway, but I figured it wouldn't hurt just to have it working if that changes later.

Also (not to derail the point of this report, but it's in the same area) couldn't the calls to 
```
    Minigotchi::monStop();
    Pwnagotchi::stopCallback();
```
that happen in the if-else block there be done just once before or after it since it's currently being done in all cases?

**Comment by dj1ch** [comment]
Fixed in this [commit](https://github.com/Pwnagotchi-Unofficial/minigotchi/commit/2453666696a584d06d75e988997c45f138253510)
