### ISSUE TITLE
Incorrectly marking everything as hidden

### ISSUE THREAD

**Issue by matrix224** [Pwnagotchi-Unofficial/minigotchi#127]
In `Deauth::printHidden()` method, it looks like it's incorrectly marking everything as hidden.

Currently it is calling `WiFi.channel(network)` to check if it's hidden, which from what I understand just returns the channel that network index is on. As such it would always be interpreted as true unless the channel was somehow actually 0.

I believe this should instead be `WiFi.isHidden(network)`

**Comment by dj1ch** [comment]
yeah, it was lol, should be able to fix that in second.

**Comment by dj1ch** [comment]
Fixed in this [commit](https://github.com/Pwnagotchi-Unofficial/minigotchi/commit/38409bd794d43f92b9505d57b3784e0dd6e1d456)
