### ISSUE TITLE
Flipper Zero GPIO/UART output

### ISSUE THREAD

**Issue by dj1ch** [Pwnagotchi-Unofficial/minigotchi#92]
Is anyone able to test if this works on a flipper by connecting this to the GPIO pins of a flipper(specifically the UART pins)? As of now I don't have a flipper and people have been asking about flipper support.

**Comment by phrohike** [comment]
Hey @dj1ch . Not sure if you still need a tester but I have a flipper, D1 Mini ESP8266, and can test this for you. Or let me know if you want me to test anything else. Thanks for the neato project. Cheers, Phrohike.

**Comment by dj1ch** [comment]
> Hey @dj1ch . Not sure if you still need a tester but I have a flipper, D1 Mini ESP8266, and can test this for you. Or let me know if you want me to test anything else. Thanks for the neato project. Cheers, Phrohike.

sure, go ahead. if you can connect it(I'm not the best at that), then compile it from the [development](https://github.com/Pwnagotchi-Unofficial/minigotchi/tree/development) branch, it should give you *something*. let me know how it goes.

**Comment by dj1ch** [comment]
Found that it worked on the flipper wifi dev board, will probably close this until further notice.
